apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  selector:
    matchLabels:
      run: my-nginx
  replicas: 2
  template:
    metadata:
      labels:
        run: my-nginx
    spec:
      containers:
      - name: my-nginx
<<<<<<< HEAD
        image: jinsu0625/test:60
=======
        image: jinsu0625/test:58
>>>>>>> de545fb8602d7835a0a5ec05884ea199549dcb76
        ports:
        - containerPort: 80
